jobs:
  bazel-steward:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: VirtusLab/bazel-steward@latest
      with:
        configuration-path: ./.bazel-steward.yaml
name: Bazel Steward
on:
  repository_dispatch:
    types: trigger-ga___bazel-steward.yml
