jobs:
  bazel_build_test_and_pmd:
    needs:
    - get_date
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Bazelisk cache
      uses: actions/cache@v3
      with:
        key: ${{runner.os}}-bazelisk-${{ hashFiles('.bazelversion') }}
        path: ~/.cache/bazelisk
    - continue-on-error: true
      name: Bazel cache
      uses: actions/cache@v3
      with:
        key: ${{runner.os}}-bazel-${{ hashFiles('.bazelversion', 'WORKSPACE', 'maven_install.json')
          }}-test-${{ needs.get_date.outputs.ymd }}
        path: ~/.cache/bazel
        restore-keys: '${{runner.os}}-bazel-${{ hashFiles(''.bazelversion'', ''WORKSPACE'',
          ''maven_install.json'') }}-test-

          ${{runner.os}}-bazel-${{ hashFiles(''.bazelversion'', ''WORKSPACE'', ''maven_install.json'')
          }}-

          ${{runner.os}}-bazel-

          '
    - continue-on-error: true
      name: Bazel build and test
      run: 'bazel test --test_output=errors --test_tag_filters=-pmd_test --build_tag_filters=-pmd_test
        -- //...

        bazel test --test_output=errors --test_tag_filters=pmd_test -- //...

        '
    - continue-on-error: true
      name: Build JAR
      run: 'mkdir workspace

        bazel build //projects/allinone:allinone_main_deploy.jar

        cp bazel-bin/projects/allinone/allinone_main_deploy.jar workspace/allinone.jar

        '
    - continue-on-error: true
      name: Save JAR
      uses: actions/upload-artifact@v3
      with:
        name: allinone_jar
        path: workspace/allinone.jar
  checkstyle:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Checkstyle cache
      uses: actions/cache@v3
      with:
        key: checkstyle-${{ hashFiles('tools/run_checkstyle.sh') }}
        path: ~/.cache/checkstyle
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Checkstyle
      run: tools/run_checkstyle.sh
  code_cov:
    needs:
    - format
    - json_template
    - get_date
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Bazelisk cache
      uses: actions/cache@v3
      with:
        key: ${{runner.os}}-bazelisk-${{ hashFiles('.bazelversion') }}
        path: ~/.cache/bazelisk
    - continue-on-error: true
      name: Bazel cache
      uses: actions/cache@v3
      with:
        key: ${{runner.os}}-bazel-${{ hashFiles('.bazelversion', 'WORKSPACE', 'maven_install.json')
          }}-junit-${{ needs.get_date.outputs.ymd }}
        path: ~/.cache/bazel
        restore-keys: '${{runner.os}}-bazel-${{ hashFiles(''.bazelversion'', ''WORKSPACE'',
          ''maven_install.json'') }}-junit-

          ${{runner.os}}-bazel-${{ hashFiles(''.bazelversion'', ''WORKSPACE'', ''maven_install.json'')
          }}-

          ${{runner.os}}-bazel-

          '
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Bazel Junit Tests and Coverage
      run: "bazel coverage //projects/... \\\n  --instrumentation_filter=\"-//projects/batfish/src/main/java/org/batfish/representation/juniper/parboiled,-//projects/batfish/src/main/java/org/batfish/vendor/check_point_management/parsing/parboiled,-//projects/batfish-common-protocol:specifier_common,-//projects/batfish/src/main/antlr4[/:],-//projects/.*/src/test[/:]\"\
        \ \\\n  --test_tag_filters=-pmd_test \\\n  --combined_report=lcov \\\n  --instrument_test_targets=false\n"
    - continue-on-error: true
      name: Generate report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: bazel-out/_coverage/_coverage_report.dat
        verbose: true
  format:
    needs:
    - get_date
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: google-java-format cache
      uses: actions/cache@v3
      with:
        key: google-java-format-${{ hashFiles('tools/fix_java_format.sh') }}
        path: ~/.cache/google-java-format
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Java Formatting
      run: tools/fix_java_format.sh --check
  get_date:
    name: ':clock: Get Date'
    outputs:
      ymd: ${{ steps.date.outputs.ymd }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: date
      name: Get current date
      run: echo "::set-output name=ymd::$(date +'%Y-%m-%d')"
  json_template:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - continue-on-error: true
      name: Install dependencies
      run: python -m pip install pytest
    - continue-on-error: true
      name: JSON Templates
      run: cd tests && pytest
name: Pre-commit
on:
  repository_dispatch:
    types: trigger-ga___pre-commit.yml
