jobs:
  scan_allinone:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: aquasecurity/trivy-action@master
      with:
        exit-code: '1'
        format: table
        ignore-unfixed: true
        image-ref: batfish/allinone:${{ inputs.tag }}
        severity: MEDIUM,HIGH,CRITICAL
  scan_batfish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: aquasecurity/trivy-action@master
      with:
        exit-code: '1'
        format: table
        ignore-unfixed: true
        image-ref: batfish/batfish:${{ inputs.tag }}
        severity: MEDIUM,HIGH,CRITICAL
name: Vulnerability Scan (reusable)
on:
  repository_dispatch:
    types: trigger-ga___reusable-vulnerability-scan.yml
